In [1]:
import numpy as np
from scipy.spatial.transform import Rotation

In [2]:
def compute_shift(arr: np.ndarray, decimal_magnitude: int = 4):
    return np.median(np.round(arr, decimals=-(decimal_magnitude - 1)), axis=0)

def is_shift_needed(arr: np.ndarray, decimal_magnitude: int = 4) -> np.bool_:
    return np.any(np.abs(arr) >= _optimal_range(decimal_magnitude))

def _optimal_range(decimal_magnitude: int = 4):
    return 10 ** decimal_magnitude

In [108]:
project_origin = np.array([300_000_01.023, 1_000_010.0001, 116.00])

In [109]:
socs = np.eye(4)
rot = Rotation.from_euler('zyx', [np.pi/2, 0, 0]).as_matrix()
translation = project_origin
socs[:3, :3] = rot
socs[:3, 3] = translation

In [148]:
x_s = np.random.rand(10, 3)*50 + [20, -40, 6.4]
print(x_s)

[[ 26.75444459 -16.71089375  51.20640705]
 [ 40.65412983   8.33474201  38.68095854]
 [ 51.94298606 -14.79118393  18.23828368]
 [ 54.83132708  -6.70337175  13.94212474]
 [ 24.51836856   3.53589351  44.38310673]
 [ 24.13401218  -4.5938234   49.23486518]
 [ 50.80758629 -32.5832077   53.25670608]
 [ 31.18763027  -1.98742031  52.82908097]
 [ 38.32801198  -0.79604648  34.70491512]
 [ 67.86693192  -1.30272064  24.19597495]]


In [149]:
x_s_1 = np.column_stack((x_s, np.ones(x_s.shape[0])))
x_p = (socs @ x_s_1.T).T[:, :3]
shift = compute_shift(x_p)
print(shift)

[30000000.  1000000.        0.]


In [153]:
x_opt = x_p - shift
print(x_opt)

[[ 17.73389375  36.75454459 167.20640705]
 [ -7.31174201  50.65422983 154.68095854]
 [ 15.81418393  61.94308606 134.23828368]
 [  7.72637174  64.83142708 129.94212474]
 [ -2.51289351  34.51846856 160.38310673]
 [  5.61682339  34.13411218 165.23486518]
 [ 33.6062077   60.80768629 169.25670608]
 [  3.01042031  41.18773027 168.82908097]
 [  1.81904648  48.32811198 150.70491512]
 [  2.32572064  77.86703192 140.19597495]]


In [154]:
print(f'SOCS: {is_shift_needed(x_s)}')
print(f'project_coords: {is_shift_needed(x_p)}')
print(f'optimal_coords: {is_shift_needed(x_opt)}')

SOCS: False
project_coords: True
optimal_coords: False


In [173]:
def socs_to_opt(arr, rotation, delta):
    rotated = (rotation @ arr.T).T
    print(delta := to_project_matrix[:3, 3] - translation_opt)
    x_optimal = rotated + delta
    print(x_optimal)
    return x_optimal

In [177]:
print(shift)
print(translation)
delta = translation - shift
print(f'{delta=}')

[30000000.  1000000.        0.]
[3.0000001e+07 1.0000100e+06 1.1600000e+02]
delta=array([  1.023 ,  10.0001, 116.    ])


In [178]:
x_optimal = socs_to_opt(x_s, socs, shift)

[  1.023   10.0001 116.    ]
[[ 17.73389375  36.75454459 167.20640705]
 [ -7.31174201  50.65422983 154.68095854]
 [ 15.81418393  61.94308606 134.23828368]
 [  7.72637174  64.83142708 129.94212474]
 [ -2.51289351  34.51846856 160.38310673]
 [  5.61682339  34.13411218 165.23486518]
 [ 33.6062077   60.80768629 169.25670608]
 [  3.01042031  41.18773027 168.82908097]
 [  1.81904648  48.32811198 150.70491512]
 [  2.32572064  77.86703192 140.19597495]]


In [49]:
from pchandler.v2.geometry.coordinates import OptimisedCartesianCoordinates

a_ = arr=np.random.rand(100,3)*400 + 1000321312
b_ = arr=np.random.rand(100,3)*400 + 1000321423
c_ = arr=np.random.rand(100,3)*400 + 1000321363
d_ = arr=np.random.rand(100,3)*400 + 1000324233
e_ = arr=np.random.rand(100,3)*400 + 1001221323
a = OptimisedCartesianCoordinates(arr=a_.copy())
b = OptimisedCartesianCoordinates(arr=b_.copy())
c = OptimisedCartesianCoordinates(arr=c_.copy())
d = OptimisedCartesianCoordinates(arr=d_.copy())
e = OptimisedCartesianCoordinates(arr=e_.copy())

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
PCD added - id(pcd)=2123976693136
PCD added - id(pcd)=2123981839712
PCD added - id(pcd)=2123981839952
PCD added - id(pcd)=2123981840192
PCD added - id(pcd)=2123981840432


In [51]:
a.local_shift

array([-6.002832e+09, -6.002832e+09, -6.002832e+09], dtype=float32)

In [ ]:
|